"""The Store seam — the typed contract every backend store must satisfy.

NINA persists orgs, sites, API keys, CLI tokens, usage, and webhook events.
Two interchangeable implementations exist:

- ``ConsoleStore`` (JSON file) — dev / single process.
- ``PgStore`` (PostgreSQL) — production, selected when ``DATABASE_URL`` is set.

This ``Store`` Protocol is the single source of truth for the surface both must
implement. It exists to stop the two from drifting (they have before — e.g. an
API-key hashing divergence that silently broke JSON↔Postgres migration). The
console depends on this abstraction, not on a concrete class; ``mypy`` checks
each implementation against it, and ``tests/test_store_protocol.py`` asserts the
method sets stay in sync at runtime.

Keep this Protocol and both implementations changed together: add a method here
when both stores gain it, never to only one.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Store(Protocol):
    # ── lifecycle ──────────────────────────────────────────────────────────
    def load(self, path: Path | None = None) -> None: ...
    def save(self) -> None: ...

    # ── orgs ───────────────────────────────────────────────────────────────
    def create_org(self, name: str, owner_email: str | None) -> dict[str, Any]: ...
    def rotate_dashboard_token(self, org_id: str) -> dict[str, Any]: ...
    def verify_dashboard_token(self, raw_token: str) -> dict[str, Any] | None: ...
    def get_org(self, org_id: str) -> dict[str, Any] | None: ...
    def list_orgs(self) -> list[dict[str, Any]]: ...
    def count_orgs(self) -> int: ...

    # ── sites ──────────────────────────────────────────────────────────────
    def create_site(
        self,
        org_id: str,
        name: str,
        base_url: str,
        *,
        locales: list[str] | None = ...,
        markets: list[str] | None = ...,
        allowed_origins: list[str] | None = ...,
        currency: str | None = ...,
        plan: str = ...,
    ) -> dict[str, Any]: ...
    def set_plan(self, site_id: str, plan: str) -> None: ...
    def attach_contract(self, site_id: str, contract: dict[str, Any]) -> None: ...
    def attach_product_catalog(self, site_id: str, catalog: list[dict[str, Any]]) -> None: ...
    def attach_llm_config(self, site_id: str, llm_config: dict[str, Any]) -> None: ...
    def update_site_fields(self, site_id: str, **kwargs: Any) -> None: ...
    def get_site(self, site_id: str) -> dict[str, Any] | None: ...
    def list_sites(self, org_id: str | None = None) -> list[dict[str, Any]]: ...
    def count_sites(self) -> int: ...
    def find_site_by_wa_number(self, wa_number_id: str) -> dict[str, Any] | None: ...
    def embed_snippet(self, site_id: str, api_url: str, manifest_url: str, pk_key: str) -> str: ...

    # ── quota / usage ──────────────────────────────────────────────────────
    def enforce_quota(self, site_id: str) -> tuple[bool, int, int | None]: ...
    def record_usage(self, site_id: str) -> None: ...
    def get_usage(self, site_id: str) -> dict[str, Any]: ...

    # ── API keys ───────────────────────────────────────────────────────────
    def issue_api_key(self, site_id: str, env: str, kind: str) -> dict[str, Any]: ...
    def resolve_key_to_site(
        self, raw_key: str, origin: str | None
    ) -> tuple[bool, dict[str, Any] | None, dict[str, Any] | None]: ...
    def verify_publishable_key(
        self, raw_key: str, site_id: str | None, origin: str | None
    ) -> tuple[bool, dict[str, Any] | None]: ...
    def get_api_key(self, key_id: str) -> dict[str, Any] | None: ...
    def list_api_keys(self) -> list[dict[str, Any]]: ...
    def list_api_keys_for_site(self, site_id: str) -> list[dict[str, Any]]: ...
    def revoke_api_key(self, key_id: str) -> None: ...
    def count_keys(self) -> int: ...

    # ── CLI tokens ─────────────────────────────────────────────────────────
    def issue_cli_token(self, org_id: str, label: str) -> dict[str, Any]: ...
    def revoke_cli_token(self, token_id: str) -> None: ...

    # ── webhook events ─────────────────────────────────────────────────────
    def push_webhook_event(self, event_type: str, payload: dict[str, Any]) -> int: ...
    def list_webhook_events(self, event_type: str | None = None) -> list[dict[str, Any]]: ...


#: The set of methods the Store contract requires. Used by the drift test to
#: assert ConsoleStore and PgStore both implement exactly this surface.
STORE_METHODS: frozenset[str] = frozenset(
    name for name in dir(Store) if not name.startswith("_")
)
